services:
  - type: web
    name: pydantic-ai-agents-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r app/requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
